import pandas as pd

INPUT_FILE = "evaluation/training_candidates.csv"
OUTPUT_FILE = "evaluation/training_candidates.csv"

BATCH_SIZE = 20

LABELS = {
    1: [
        "playback_issue",
        "account_access",
        "other_unclear",
        "app_technical_issue",
        "feature_feedback",
        "app_technical_issue",
        "app_technical_issue",
        "other_unclear",
        "premium_subscription",
        "other_unclear",
        "content_library",
        "app_technical_issue",
        "feature_feedback",
        "app_technical_issue",
        "feature_feedback",
        "content_library",
        "account_access",
        "app_technical_issue",
        "other_unclear",
        "app_technical_issue",
    ],

    2: [
        "app_technical_issue",
        "download_offline",
        "app_technical_issue",
        "content_library",
        "app_technical_issue",
        "billing_payment",
        "playback_issue",
        "other_unclear",
        "feature_feedback",
        "content_library",
        "feature_feedback",
        "feature_feedback",
        "other_unclear",
        "app_technical_issue",
        "other_unclear",
        "app_technical_issue",
        "other_unclear",
        "other_unclear",
        "family_plan",
        "billing_payment",
    ],

        3: [
        "content_library",
        "premium_subscription",
        "premium_subscription",
        "content_library",
        "feature_feedback",
        "content_library",
        "playback_issue",
        "account_access",
        "content_library",
        "app_technical_issue",
        "download_offline",
        "app_technical_issue",
        "playback_issue",
        "download_offline",
        "content_library",
        "billing_payment",
        "account_access",
        "other_unclear",
        "account_access",
        "content_library",
    ],
        4: [
        "content_library",
        "app_technical_issue",
        "account_access",
        "feature_feedback",
        "family_plan",
        "content_library",
        "download_offline",
        "account_access",
        "playback_issue",
        "student_plan",
        "content_library",
        "other_unclear",
        "feature_feedback",
        "app_technical_issue",
        "family_plan",
        "feature_feedback",
        "content_library",
        "content_library",
        "other_unclear",
        "download_offline",
    ],
        5: [
        "content_library",
        "feature_feedback",
        "feature_feedback",
        "feature_feedback",
        "playback_issue",
        "account_access",
        "other_unclear",
        "app_technical_issue",
        "billing_payment",
        "premium_subscription",
        "other_unclear",
        "billing_payment",
        "feature_feedback",
        "app_technical_issue",
        "content_library",
        "student_plan",
        "playback_issue",
        "other_unclear",
        "content_library",
        "feature_feedback",
    ],
        6: [
        "content_library",
        "billing_payment",
        "other_unclear",
        "premium_subscription",
        "other_unclear",
        "playback_issue",
        "feature_feedback",
        "playback_issue",
        "account_access",
        "account_access",
        "content_library",
        "other_unclear",
        "content_library",
        "student_plan",
        "feature_feedback",
        "premium_subscription",
        "account_access",
        "other_unclear",
        "content_library",
        "playback_issue",
    ],
        7: [
        "account_access",
        "playback_issue",
        "feature_feedback",
        "content_library",
        "feature_feedback",
        "feature_feedback",
        "other_unclear",
        "app_technical_issue",
        "feature_feedback",
        "playback_issue",
        "student_plan",
        "app_technical_issue",
        "feature_feedback",
        "other_unclear",
        "other_unclear",
        "other_unclear",
        "account_access",
        "premium_subscription",
        "billing_payment",
        "other_unclear",
    ],
        8: [
        "premium_subscription",
        "feature_feedback",
        "playback_issue",
        "app_technical_issue",
        "family_plan",
        "playback_issue",
        "account_access",
        "other_unclear",
        "other_unclear",
        "billing_payment",
        "premium_subscription",
        "app_technical_issue",
        "other_unclear",
        "feature_feedback",
        "other_unclear",
        "playback_issue",
        "playback_issue",
        "app_technical_issue",
        "content_library",
        "app_technical_issue",
    ],
        9: [
        "app_technical_issue",
        "account_access",
        "other_unclear",
        "app_technical_issue",
        "premium_subscription",
        "content_library",
        "app_technical_issue",
        "other_unclear",
        "content_library",
        "other_unclear",
        "app_technical_issue",
        "content_library",
        "app_technical_issue",
        "app_technical_issue",
        "other_unclear",
        "feature_feedback",
        "family_plan",
        "other_unclear",
        "other_unclear",
        "account_access",
    ],
        10: [
        "app_technical_issue",
        "other_unclear",
        "feature_feedback",
        "content_library",
        "student_plan",
        "app_technical_issue",
        "family_plan",
        "feature_feedback",
        "account_access",
        "feature_feedback",
        "playback_issue",
        "account_access",
        "feature_feedback",
        "other_unclear",
        "other_unclear",
        "family_plan",
        "feature_feedback",
        "other_unclear",
        "feature_feedback",
        "other_unclear",
    ],
        11: [
        "content_library",
        "other_unclear",
        "family_plan",
        "account_access",
        "content_library",
        "playback_issue",
        "feature_feedback",
        "family_plan",
        "other_unclear",
        "content_library",
        "other_unclear",
        "account_access",
        "other_unclear",
        "feature_feedback",
        "feature_feedback",
        "download_offline",
        "billing_payment",
        "student_plan",
        "other_unclear",
        "content_library",
    ],
        12: [
        "family_plan",
        "student_plan",
        "billing_payment",
        "other_unclear",
        "account_access",
        "other_unclear",
        "content_library",
        "feature_feedback",
        "feature_feedback",
        "student_plan",
        "other_unclear",
        "other_unclear",
        "content_library",
        "billing_payment",
        "other_unclear",
        "app_technical_issue",
        "feature_feedback",
        "billing_payment",
        "app_technical_issue",
        "billing_payment",
    ],
        13: [
        "feature_feedback",
        "account_access",
        "content_library",
        "app_technical_issue",
        "billing_payment",
        "premium_subscription",
        "other_unclear",
        "account_access",
        "content_library",
        "other_unclear",
        "other_unclear",
        "content_library",
        "premium_subscription",
        "feature_feedback",
        "other_unclear",
        "other_unclear",
        "playback_issue",
        "content_library",
        "billing_payment",
        "premium_subscription",
    ],
        14: [
        "premium_subscription",
        "other_unclear",
        "billing_payment",
        "download_offline",
        "billing_payment",
        "content_library",
        "family_plan",
        "content_library",
        "billing_payment",
        "student_plan",
        "family_plan",
        "feature_feedback",
        "content_library",
        "other_unclear",
        "premium_subscription",
        "app_technical_issue",
        "feature_feedback",
        "content_library",
        "family_plan",
        "app_technical_issue",
    ],
        15: [
        "content_library",
        "app_technical_issue",
        "account_access",
        "app_technical_issue",
        "billing_payment",
        "other_unclear",
        "download_offline",
        "premium_subscription",
        "other_unclear",
        "content_library",
        "family_plan",
        "app_technical_issue",
        "app_technical_issue",
        "content_library",
        "content_library",
        "premium_subscription",
        "family_plan",
        "app_technical_issue",
        "premium_subscription",
        "feature_feedback",
    ],
        16: [
        "other_unclear",
        "other_unclear",
        "app_technical_issue",
        "other_unclear",
        "content_library",
        "billing_payment",
        "playback_issue",
        "feature_feedback",
        "app_technical_issue",
        "content_library",
        "feature_feedback",
        "account_access",
        "playback_issue",
        "app_technical_issue",
        "app_technical_issue",
        "account_access",
        "account_access",
        "app_technical_issue",
        "other_unclear",
        "download_offline",
    ],
        17: [
        "premium_subscription",
        "other_unclear",
        "other_unclear",
        "account_access",
        "other_unclear",
        "content_library",
        "other_unclear",
        "family_plan",
        "feature_feedback",
        "app_technical_issue",
        "playback_issue",
        "playback_issue",
        "account_access",
        "account_access",
        "premium_subscription",
        "playback_issue",
        "feature_feedback",
        "feature_feedback",
        "other_unclear",
        "app_technical_issue",
    ],
        18: [
        "feature_feedback",
        "family_plan",
        "playback_issue",
        "playback_issue",
        "other_unclear",
        "account_access",
        "app_technical_issue",
        "app_technical_issue",
        "playback_issue",
        "app_technical_issue",
        "premium_subscription",
        "feature_feedback",
        "app_technical_issue",
        "download_offline",
        "feature_feedback",
        "app_technical_issue",
        "billing_payment",
        "app_technical_issue",
        "playback_issue",
        "app_technical_issue",
    ],
        19: [
        "other_unclear",
        "playback_issue",
        "billing_payment",
        "content_library",
        "billing_payment",
        "premium_subscription",
        "other_unclear",
        "app_technical_issue",
        "account_access",
        "feature_feedback",
        "feature_feedback",
        "playback_issue",
        "billing_payment",
        "feature_feedback",
        "content_library",
        "feature_feedback",
        "app_technical_issue",
        "other_unclear",
        "app_technical_issue",
        "feature_feedback",
    ],
        20: [
        "account_access",
        "other_unclear",
        "other_unclear",
        "content_library",
        "other_unclear",
        "app_technical_issue",
        "premium_subscription",
        "feature_feedback",
        "feature_feedback",
        "premium_subscription",
        "billing_payment",
        "student_plan",
        "feature_feedback",
        "other_unclear",
        "other_unclear",
        "content_library",
        "student_plan",
        "app_technical_issue",
        "app_technical_issue",
        "playback_issue",
    ],
        21: [
        "app_technical_issue",
        "feature_feedback",
        "content_library",
        "other_unclear",
        "other_unclear",
        "other_unclear",
        "content_library",
        "account_access",
        "app_technical_issue",
        "premium_subscription",
        "feature_feedback",
        "playback_issue",
        "other_unclear",
        "other_unclear",
        "other_unclear",
        "other_unclear",
        "other_unclear",
        "feature_feedback",
        "feature_feedback",
        "other_unclear",
    ],
        22: [
        "premium_subscription",
        "billing_payment",
        "playback_issue",
        "premium_subscription",
        "feature_feedback",
        "other_unclear",
        "family_plan",
        "content_library",
        "other_unclear",
        "feature_feedback",
        "playback_issue",
        "app_technical_issue",
        "content_library",
        "student_plan",
        "feature_feedback",
        "playback_issue",
        "app_technical_issue",
        "app_technical_issue",
        "billing_payment",
        "content_library",
    ],
        23: [
        "account_access",
        "content_library",
        "app_technical_issue",
        "playback_issue",
        "account_access",
        "feature_feedback",
        "content_library",
        "download_offline",
        "feature_feedback",
        "other_unclear",
        "feature_feedback",
        "app_technical_issue",
        "feature_feedback",
        "content_library",
        "download_offline",
        "app_technical_issue",
        "other_unclear",
        "content_library",
        "playback_issue",
        "account_access",
    ],
        24: [
        "content_library",
        "other_unclear",
        "account_access",
        "other_unclear",
        "content_library",
        "feature_feedback",
        "playback_issue",
        "billing_payment",
        "content_library",
        "feature_feedback",
        "student_plan",
        "app_technical_issue",
        "account_access",
        "app_technical_issue",
        "content_library",
        "other_unclear",
        "student_plan",
        "account_access",
        "other_unclear",
        "app_technical_issue",
    ],
        25: [
        "family_plan",
        "playback_issue",
        "playback_issue",
        "feature_feedback",
        "app_technical_issue",
        "other_unclear",
        "app_technical_issue",
        "student_plan",
        "app_technical_issue",
        "other_unclear",
        "app_technical_issue",
        "app_technical_issue",
        "account_access",
        "family_plan",
        "feature_feedback",
        "content_library",
        "app_technical_issue",
        "app_technical_issue",
        "premium_subscription",
        "billing_payment",
    ],
        26: [
        "other_unclear",
        "student_plan",
        "app_technical_issue",
        "other_unclear",
        "feature_feedback",
        "family_plan",
        "content_library",
        "app_technical_issue",
        "app_technical_issue",
        "content_library",
        "student_plan",
        "other_unclear",
        "app_technical_issue",
        "feature_feedback",
        "playback_issue",
        "feature_feedback",
        "feature_feedback",
        "content_library",
        "other_unclear",
        "other_unclear",
    ],
        27: [
        "family_plan",
        "feature_feedback",
        "content_library",
        "account_access",
        "feature_feedback",
        "content_library",
        "feature_feedback",
        "other_unclear",
        "premium_subscription",
        "other_unclear",
        "other_unclear",
        "other_unclear",
        "feature_feedback",
        "app_technical_issue",
        "download_offline",
        "feature_feedback",
        "account_access",
        "other_unclear",
        "feature_feedback",
        "account_access",
    ],
        28: [
        "playback_issue",
        "feature_feedback",
        "feature_feedback",
        "billing_payment",
        "other_unclear",
        "feature_feedback",
        "download_offline",
        "premium_subscription",
        "feature_feedback",
        "app_technical_issue",
    ],
}


def main():
    df = pd.read_csv(INPUT_FILE)

    df["training_intent"] = df["training_intent"].astype("object")

    batch_number = int(input("Enter batch number: "))

    if batch_number not in LABELS:
        print("No labels available for this batch yet.")
        return

    labels = LABELS[batch_number]

    start = (batch_number - 1) * BATCH_SIZE
    end = start + BATCH_SIZE

    df.loc[start:end - 1, "training_intent"] = labels

    df.to_csv(OUTPUT_FILE, index=False)

    print(f"Batch {batch_number} labeled successfully.")
    print()

    print(
        df.loc[start:end - 1, [
            "customer_tweet_id",
            "training_intent"
        ]].to_string(index=False)
    )


if __name__ == "__main__":
    main()